namespace TrProtocol.Models;

public enum LeashedEntityPrototype : int {
    LeashedKite = 1,
    WalkerLeashedCritter,
    AquaticWalkerLeashedCritter,
    CrawlerLeashedCritter,
    SnailLeashedCritter,
    TurtleLeashedCritter,
    RunnerLeashedCritter,
    FlyerLeashedCritter,
    NormalButterflyLeashedCritter,
    EmpressButterflyLeashedCritter,
    HellButterflyLeashedCritter,
    FireflyLeashedCritter,
    ShimmerFlyLeashedCritter,
    DragonflyLeashedCritter,
    CrawlingFlyLeashedCritter,
    BirdLeashedCritter,
    WaterfowlLeashedCritter,
    FishLeashedCritter,
    FairyLeashedCritter,
    JumperLeashedCritter,
    WaterStriderLeashedCritter,
}
