using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Text;
using TrProtocol.Attributes;
using TrProtocol.Exceptions;
using TrProtocol.Interfaces;
using TrProtocol.SerializerGenerator.Internal.Diagnostics;
using TrProtocol.SerializerGenerator.Internal.Extensions;
using TrProtocol.SerializerGenerator.Internal.Models;
using TrProtocol.SerializerGenerator.Internal.Serialization;
using TrProtocol.SerializerGenerator.Internal.Serialization.TypeSerializers;
using TrProtocol.SerializerGenerator.Internal.SyntaxTemplates;
using TrProtocol.SerializerGenerator.Internal.Utilities;

namespace TrProtocol.SerializerGenerator.Internal.Generation;

internal static class TypeFileEmitter
{
    public static void Emit(
        SourceProductionContext context,
        CompilationContext compilationContext,
        TypeSerializerDispatcher typeSerializerDispatcher,
        ProtocolTypeData model,
        Func<TypeDeclarationSyntax, ProtocolTypeInfo> transform) {
        var modelSym = model.DefSymbol;
        if (model.IsPolymorphic || !model.HasSeriInterface || model.IsInterface) {
            return;
        }

        try {
            List<string> memberNullables = [];
            var file = new SourceCodeWriter(1024 * 4);
            file.WriteLine();
            file.WriteLine("// <auto-generated>");
            var usingTarget = file.WriteLine();
            file.Write($"namespace {model.Namespace} ");
            file.BlockWrite((namespaceBlock) => {

                var classNode = namespaceBlock.WriteTypeDefinition(model);
                classNode.WriteAutoDiscriminator(model);

                #region Add Global ID
                if (model.GlobalID >= 0) {
                    classNode.WriteLine($"public static int GlobalID => {model.GlobalID};");
                }
                #endregion

                #region Add type constructors and special behavior

                List<(string memberName, string memberType)> externalMembers = GenerationHelpers.GetExternalMembers(modelSym);
                var (externalMemberParams, _) = GenerationHelpers.GetExternalMemberParams(externalMembers);
                if (model.IsSideSpecific) {

                    if (!model.IsNetPacket) {
                        throw new DiagnosticException(
                            Diagnostic.Create(
                                new DiagnosticDescriptor(
                                    "SCG13",
                                    $"Invaild type DefSymbol",
                                    $"This interface '{nameof(ISideSpecific)}' is only allowed to be inherited by packets",
                                    "",
                                    DiagnosticSeverity.Error,
                                    true),
                                model.DefSyntax.GetLocation()));
                    }
                    classNode.WriteLine($"public bool {nameof(ISideSpecific.IsServerSide)} {{ get; set; }}");
                }

                if (model.IsLengthAware) {
                    if (model.HasExtraData) {
                        classNode.WriteLine($"public byte[] {nameof(IExtraData.ExtraData)} {{ get; set; }} = [];");
                    }
                    classNode.Write($"public {model.TypeName}(ref void* ptr, void* ptr_end{(model.IsSideSpecific ? ", bool isServerSide" : "")}{externalMemberParams})");
                    classNode.BlockWrite((source) => {
                        source.WriteLine($"ReadContent(ref ptr, ptr_end);");
                    });
                }
                else {
                    classNode.Write($"public {model.TypeName}(ref void* ptr{(model.IsSideSpecific ? ", bool isServerSide" : "")}{externalMemberParams})");
                    classNode.BlockWrite((source) => {
                        if (model.IsSideSpecific) {
                            source.WriteLine($"{nameof(ISideSpecific.IsServerSide)} = isServerSide;");
                        }
                        foreach (var m in externalMembers) {
                            source.WriteLine($"{m.memberName} = _{m.memberName};");
                        }
                        source.WriteLine($"ReadContent(ref ptr);");
                    });
                }

                if (model.PacketAutoSeri) {
                    List<SerializationExpandContext> defaults = new(model.Members.Count);
                    var initMembers = model.Members.Where(m => !m.Attributes.Any(a => a.AttributeMatch<InitNullableAttribute>())).ToArray();
                    int shouldCreateNewConstructor = -1;
                    var parameters = initMembers.Select(m => {
                        if (m.Attributes.Any(a => a.AttributeMatch<InitDefaultValueAttribute>())) {
                            if (shouldCreateNewConstructor == -1) {
                                shouldCreateNewConstructor = 0;
                            }
                            if (m.IsNullable) {
                                defaults.Add(m);
                                return null;
                            }
                            if (compilationContext.TryGetTypeSymbol(m.MemberType.GetTypeSymbolName(), out var mtsym, model.Namespace, model.Imports) && mtsym.IsUnmanagedType) {
                                defaults.Add(m);
                                return null;
                            }
                        }
                        if (shouldCreateNewConstructor == 0) {
                            shouldCreateNewConstructor = 1;
                        }
                        return $"{m.MemberType} _{m.MemberName}";
                    }).Where(s => s is not null).ToList();

                    var parameters_extra = new List<string>();
                    if (model.HasExtraData) {
                        parameters_extra.Add($"byte[] _{nameof(IExtraData.ExtraData)}");
                    }
                    if (model.IsSideSpecific) {
                        parameters_extra.Add($"bool _{nameof(ISideSpecific.IsServerSide)}");
                    }
                    var parameters_defaults = defaults.Select(m => $"{m.MemberType} _{m.MemberName} = default").ToList();

                    if (shouldCreateNewConstructor == 1 || (parameters_defaults.Count > 0 && (model.HasExtraData || model.IsSideSpecific))) {
                        classNode.Write($"public {model.TypeName}({string.Join(", ", initMembers.Select(m => $"{m.MemberType} _{m.MemberName}").Concat(parameters_extra))}) ");
                        classNode.BlockWrite((source) => {
                            if (model.IsSideSpecific) {
                                source.WriteLine($"this.{nameof(ISideSpecific.IsServerSide)} = _{nameof(ISideSpecific.IsServerSide)};");
                            }
                            foreach (var m in initMembers) {
                                source.WriteLine($"this.{m.MemberName} = _{m.MemberName};");
                            }
                            if (model.HasExtraData) {
                                source.WriteLine($"this.{nameof(IExtraData.ExtraData)} = _{nameof(IExtraData.ExtraData)};");
                            }
                        });
                    }
                    classNode.Write($"public {model.TypeName}({string.Join(", ", parameters.Concat(parameters_extra).Concat(parameters_defaults))}) ");
                    classNode.BlockWrite((source) => {
                        if (model.IsSideSpecific) {
                            source.WriteLine($"this.{nameof(ISideSpecific.IsServerSide)} = _{nameof(ISideSpecific.IsServerSide)};");
                        }
                        foreach (var m in initMembers) {
                            source.WriteLine($"this.{m.MemberName} = _{m.MemberName};");
                        }
                        if (model.HasExtraData) {
                            source.WriteLine($"this.{nameof(IExtraData.ExtraData)} = _{nameof(IExtraData.ExtraData)};");
                        }
                    });
                }

                if (model.PacketManualSeri) {
                    return;
                }
                #endregion

                #region WriteContent

                var writeNode = new BlockNode(classNode);
                var readNode = new BlockNode(classNode);

                writeNode.WriteLine("var ptr_current = ptr;");
                writeNode.WriteLine();

                if (model.IsConcreteImpl) {
                    foreach (var inherit in AbstractModelInheritanceResolver.ExtractInheritanceChain(modelSym)) {
                        if (inherit.HasAbstractModelAttribute(out var info)) {
                            writeNode.WriteLine($"Unsafe.Write(ptr_current, ({info.EnumUnderlyingTypeName}){info.discriminatorPropertyName});");
                            writeNode.WriteLine($"ptr_current = Unsafe.Add<{info.EnumUnderlyingTypeName}>(ptr_current, 1);");
                            writeNode.WriteLine();
                        }
                    }
                }

                readNode.WriteLine();

                if (model.CompressData != default) {
                    writeNode.WriteLine($"var ptr_compressed = ptr_current;");
                    writeNode.WriteLine($"var rawBuffer = ArrayPool<byte>.Shared.Rent({model.CompressData.bufferSize});");
                    writeNode.Write("fixed (void* ptr_rawdata = rawBuffer)");

                    readNode.WriteLine($"var decompressedBuffer = ArrayPool<byte>.Shared.Rent({model.CompressData.bufferSize});");
                    readNode.Write("fixed (void* ptr_decompressed = decompressedBuffer)");

                    (writeNode, readNode).BlockWrite((writeNode, readNode) => {
                        writeNode.WriteLine("ptr_current = ptr_rawdata;");

                        readNode.WriteLine("var ptr_current = ptr_decompressed;");
                        readNode.WriteLine($"CommonCode.ReadDecompressedData(ptr, ref ptr_current, (int)((long)ptr_end - (long)ptr));");
                        readNode.WriteLine("ptr_current = ptr_decompressed;");

                        MemberSerializationEmitter.Emit(context, typeSerializerDispatcher, model, modelSym, memberNullables, writeNode, readNode, transform);
                        writeNode.WriteLine($"CommonCode.WriteCompressedData(ptr_rawdata, ref ptr_compressed, (int)((long)ptr_current - (long)ptr_rawdata), {model.CompressData.compressLevel});");
                        writeNode.WriteLine($"ArrayPool<byte>.Shared.Return(rawBuffer);");
                        writeNode.WriteLine("ptr = ptr_compressed;");
                    });
                    readNode.WriteLine("ptr = ptr_end;");
                    readNode.WriteLine($"ArrayPool<byte>.Shared.Return(decompressedBuffer);");
                }
                else {
                    readNode.WriteLine("var ptr_current = ptr;");

                    MemberSerializationEmitter.Emit(context, typeSerializerDispatcher, model, modelSym, memberNullables, writeNode, readNode, transform);
                    writeNode.WriteLine("ptr = ptr_current;");
                    readNode.WriteLine();
                    if (model.HasExtraData) {
                        writeNode.WriteLine($"Marshal.Copy({nameof(IExtraData.ExtraData)}, 0, (IntPtr)ptr_current, {nameof(IExtraData.ExtraData)}.Length);");
                        writeNode.WriteLine($"ptr_current = Unsafe.Add<byte>(ptr_current, {nameof(IExtraData.ExtraData)}.Length);");

                        readNode.WriteLine("var restContentSize = (int)((long)ptr_end - (long)ptr_current);");
                        readNode.WriteLine($"{nameof(IExtraData.ExtraData)} = new byte[restContentSize];");
                        readNode.WriteLine($"Marshal.Copy((IntPtr)ptr_current, {nameof(IExtraData.ExtraData)}, 0, restContentSize);");
                        readNode.WriteLine("ptr = ptr_end;");
                    }
                    else {
                        readNode.WriteLine("ptr = ptr_current;");
                    }
                }

                if (!GenerationHelpers.HasWriteContent(modelSym)) {
                    classNode.Write($"public unsafe {((model.IsConcreteImpl && !model.IsValueType) ? "override " : "readonly ")}void WriteContent(ref void* ptr) ");
                    classNode.Sources.Add(writeNode);
                }
                #endregion

                #region ReadContent

                var hasReadContent = GenerationHelpers.HasReadContent(modelSym);
                var hasReadContentLengthAware = model.IsLengthAware && GenerationHelpers.HasReadContentLengthAware(modelSym);

                if (model.IsLengthAware) {
                    if (!hasReadContent) {
                        classNode.WriteLine("/// <summary>");
                        classNode.WriteLine("/// This operation is not supported and always throws a System.NotSupportedException.");
                        classNode.WriteLine("/// </summary>");
                        classNode.WriteLine($"[Obsolete]");
                        if ((model.IsConcreteImpl && !model.IsValueType)) {
                            classNode.WriteLine($"public override void ReadContent(ref void* ptr) => throw new {nameof(NotSupportedException)}();");
                        }
                        else {
                            classNode.WriteLine($"void {nameof(IBinarySerializable)}.ReadContent(ref void* ptr) => throw new {nameof(NotSupportedException)}();");
                        }
                    }

                    if (!hasReadContentLengthAware) {
                        classNode.WriteLine($"[MemberNotNull({string.Join(", ", memberNullables.Select(m => $"nameof({m})"))})]");
                        classNode.Write($"public unsafe void ReadContent(ref void* ptr, void* ptr_end) ");
                        classNode.Sources.Add(readNode);
                    }
                }
                else {
                    if (!hasReadContent) {
                        classNode.WriteLine($"[MemberNotNull({string.Join(", ", memberNullables.Select(m => $"nameof({m})"))})]");
                        classNode.Write($"public unsafe {((model.IsConcreteImpl && !model.IsValueType) ? "override " : "")}void ReadContent(ref void* ptr) ");
                        classNode.Sources.Add(readNode);
                    }
                }
                #endregion
            });

            #region Write using
            foreach (var us in model.Imports.Concat(GeneratorUsings.NecessaryUsings).Distinct()) {
                usingTarget.NewLineAfter($"using {us};");
            }
            foreach (var staticUsing in model.StaticImports) {
                usingTarget.NewLineAfter($"using static {staticUsing};");
            }
            #endregion

            context.AddSource($"{modelSym.GetFullName()}.seri.g.cs", SourceText.From(file.ToString(), Encoding.UTF8));
        }
        catch (DiagnosticException de) {
            context.ReportDiagnostic(de.Diagnostic);
        }
    }
}
